remote_theme: pmarsceill/just-the-docs
color_scheme: dark
title: GolfClashInfo
email: GolfClashInfo@gmail.com
baseurl: ""
url: "https://www.golfclashinfo.com"
twitter_username: GolfClashInfo
github_username:  GolfClashInfo
